#!/usr/bin/env node
// gen.mjs — embed dracondex_setup.sql into both app front-ends.
//
// The installer script has to be available to the app at RUNTIME, in a
// packaged build, on both sides: Electron ships only electron/** plus
// src/assets/brand/** (package.json -> build.files), and Flutter can only see
// files under flutter/. Neither can read src/supabase/setup/*.sql once built,
// so the SQL is embedded as a source constant on each side and this script is
// what keeps those two copies honest.
//
//   node src/supabase/setup/gen.mjs           regenerate both constants
//   node src/supabase/setup/gen.mjs --check   compare only; exit 1 if stale
//
// Edit dracondex_setup.sql, never the generated files.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
// supabase/setup/ -> repo root. Same reason as schema/generate.mjs: the two
// consuming trees are separate repositories now, so both outputs land in
// this repo's generated/ and are vendored from there.
const root = path.dirname(path.dirname(here));
const check = process.argv.includes('--check');

const sqlPath = path.join(here, 'dracondex_setup.sql');
const sql = fs.readFileSync(sqlPath, 'utf8');

// The version the script stamps into dracondex_meta. Read from the SQL rather
// than duplicated here so there is exactly one place to bump it.
const version = /^-- DRACONDEX_SCHEMA_VERSION: (\d+)$/m.exec(sql)?.[1];
if (!version) {
  console.error('gen: dracondex_setup.sql is missing its "-- DRACONDEX_SCHEMA_VERSION: <n>" line');
  process.exit(1);
}

// What "check tables" verifies. Mirrors the two array literals inside
// dracondex_schema_status() — kept here as the client-side expectation so an
// OLD project (one whose installed status function knows fewer objects) still
// gets checked against what THIS app build needs.
const TABLES = ['sync_vault', 'sync_account', 'dracondex_meta'];
const FUNCTIONS = [
  'token_sync_push', 'token_sync_status', 'token_sync_delete',
  'token_sync_pull_own', 'token_sync_pull_by_token',
];

const BANNER = 'GENERATED by src/supabase/setup/gen.mjs from dracondex_setup.sql — do not edit.';

// JSON's string escaping is a subset of Dart's, so JSON.stringify gets the
// quotes, backslashes and newlines right — but Dart also treats a bare `$` as
// the start of an interpolation, and this SQL is full of `$$`-quoted function
// bodies. Missing that turns the whole constant into a compile error (or,
// worse, into silently different SQL), so escape it explicitly.
const dartString = (str) => JSON.stringify(str).replace(/\$/g, '\\$');

const jsOut = `'use strict';
// ${BANNER}
// Run \`node src/supabase/setup/gen.mjs\` after editing the SQL.
const SUPABASE_SCHEMA_VERSION = ${version};
const SUPABASE_REQUIRED_TABLES = ${JSON.stringify(TABLES)};
const SUPABASE_REQUIRED_FUNCTIONS = ${JSON.stringify(FUNCTIONS)};
const SUPABASE_SETUP_SQL = ${JSON.stringify(sql)};

module.exports = {
  SUPABASE_SCHEMA_VERSION,
  SUPABASE_REQUIRED_TABLES,
  SUPABASE_REQUIRED_FUNCTIONS,
  SUPABASE_SETUP_SQL,
};
`;

const dartOut = `// ${BANNER}
// Run \`node src/supabase/setup/gen.mjs\` after editing the SQL.
library;

const int kSupabaseSchemaVersion = ${version};

const List<String> kSupabaseRequiredTables = ${JSON.stringify(TABLES)};

const List<String> kSupabaseRequiredFunctions = ${JSON.stringify(FUNCTIONS)};

const String kSupabaseSetupSql = ${dartString(sql)};
`;

const TARGETS = [
  ['generated/electron/supabase-schema.js', jsOut],
  ['generated/flutter/supabase_schema.dart', dartOut],
];

let stale = 0;
let wrote = 0;
for (const [rel, content] of TARGETS) {
  const dest = path.join(root, rel);
  const current = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
  if (current === content) continue;
  if (check) {
    console.error(`out of sync: ${rel} does not match dracondex_setup.sql`);
    stale++;
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content);
    console.log(`wrote ${rel}`);
    wrote++;
  }
}

if (check) {
  if (stale) { console.error(`gen --check: ${stale} file(s) stale — run: node src/supabase/setup/gen.mjs`); process.exit(1); }
  console.log('gen --check: generated files match dracondex_setup.sql');
} else {
  console.log(wrote ? `gen: ${wrote} file(s) updated (schema v${version})` : `gen: already up to date (schema v${version})`);
}
